sudo: required

services:
  - docker

before_install:
  - docker build -t docker-postfix .
  - docker run docker-postfix /bin/sh -c "echo \"OK\""

before_script:
  - touch .env

script:
  - echo "OK"
